Derive Instances For Recursive Data Types
zio/zio-prelude pull request #1081
Opened 2023-02-15 15:10 UTC by adamgfraser

2023-02-15 23:57 UTC, sideeffffect approved these changes
Sweet :+1:

2023-02-16 00:02 UTC, sideeffffect requested changes
typo :smile_cat:

2023-02-16 00:02 UTC, sideeffffect commented on core-tests/shared/src/test/scala-3/zio/prelude/DerivationSpec.scala
> +          assertTrue(NonEmptyList.Cons(1, NonEmptyList.Single(2)) != NonEmptyList.Cons(1, NonEmptyList.Single(3)))
```suggestion
          assertTrue(NonEmptyList.Cons(1, NonEmptyList.Single(2)) === NonEmptyList.Cons(1, NonEmptyList.Single(2))) &&
          assertTrue(NonEmptyList.Cons(1, NonEmptyList.Single(2)) !== NonEmptyList.Cons(1, NonEmptyList.Single(3)))
```

2023-02-16 00:22 UTC, adamgfraser commented on core-tests/shared/src/test/scala-3/zio/prelude/DerivationSpec.scala
> +          assertTrue(NonEmptyList.Cons(1, NonEmptyList.Single(2)) != NonEmptyList.Cons(1, NonEmptyList.Single(3)))
Oops!

2023-02-16 01:18 UTC, sideeffffect approved these changes
I wanted to write that "we're all human", but that I realized that you're clearly not a mere human with all the work you're doing, so I have to retract that :smile:

2023-02-16 01:36 UTC, adamgfraser commented
Definitely human! 😃

2023-02-16 01:36 UTC, merged